// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTarget(arg1, arg2) {
  return window['go']['main']['App']['AddTarget'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDiagramConfig() {
  return window['go']['main']['App']['GetDiagramConfig']();
}

export function GetReport(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetReport'](arg1, arg2, arg3);
}

export function GetTargets() {
  return window['go']['main']['App']['GetTargets']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function RemoveTarget(arg1) {
  return window['go']['main']['App']['RemoveTarget'](arg1);
}

export function SetTargetActive(arg1, arg2) {
  return window['go']['main']['App']['SetTargetActive'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
