// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {config} from '../models';

export function AddTarget(arg1:string,arg2:string):Promise<domain.Host>;

export function GetConfig():Promise<config.AppConfig>;

export function GetDiagramConfig():Promise<config.NetworkDiagramConfig>;

export function GetReport(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetTargets():Promise<Array<domain.Host>>;

export function OpenPath(arg1:string):Promise<void>;

export function RemoveTarget(arg1:string):Promise<void>;

export function SetTargetActive(arg1:string,arg2:boolean):Promise<void>;

export function UpdateConfig(arg1:config.AppConfig):Promise<void>;
